import { Router } from "express";
import auth from "./auth.routes.js";
import users from "./users.routes.js";
import roles from "./roles.routes.js";
import permissions from "./permissions.routes.js";
import userRoles from "./userRoles.routes.js";
import rolePermissions from "./rolePermissions.routes.js";
import services from "./services.routes.js";
import serviceTypes from "./serviceTypes.routes.js";
import serviceStatuses from "./serviceStatuses.routes.js";
import serviceHistory from "./serviceHistory.routes.js";
import serviceMessages from "./serviceMessages.routes.js";
import payments from "./payments.routes.js";
import quotes from "./quotes.routes.js";
import paymentMethods from "./paymentMethods.routes.js";
import addresses from "./addresses.routes.js";
import countries from "./countries.routes.js";
import states from "./states.routes.js";
import cities from "./cities.routes.js";
import postalCodes from "./postalCodes.routes.js";
import documents from "./documents.routes.js";
import adminLogs from "./adminLogs.routes.js";
import reviews from "./reviews.routes.js";
import workers from "./workers.routes.js";
import admin from "./admin.routes.js";

const router = Router();

router.use("/auth", auth);
router.use("/users", users);
router.use("/roles", roles);
router.use("/permissions", permissions);
router.use("/user-roles", userRoles);
router.use("/role-permissions", rolePermissions);
router.use("/services", services);
router.use("/service-types", serviceTypes);
router.use("/service-statuses", serviceStatuses);
router.use("/service-history", serviceHistory);
router.use("/service-messages", serviceMessages);
router.use("/payments", payments);
router.use("/quotes", quotes);
router.use("/payment-methods", paymentMethods);
router.use("/addresses", addresses);
router.use("/countries", countries);
router.use("/states", states);
router.use("/cities", cities);
router.use("/postal-codes", postalCodes);
router.use("/documents", documents);
router.use("/admin-logs", adminLogs);
router.use("/reviews", reviews);
router.use("/workers", workers);
router.use("/admin", admin);

export default router;